server:
  port: 8881
spring:
  datasource:
    jdbcUrl: jdbc:postgresql://maqshost:5432/spring-jpa
    username: postgres
    password: postgres
    initialize: false
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 10000
  jpa:
    show-sql: true
    database: postgresql
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        id.new_generator_mappings: false
        format_sql: true
        enable_lazy_load_no_trans: true
logging:
  level:
    org.hibernate:
      engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

logging.level.com.maqs: DEBUG
